runtime: python39

entrypoint: gunicorn -b :$PORT main:app

env_variables:
  GOOGLE_APPLICATION_CREDENTIALS: 'static/tts-key.json'

handlers:
  - url: /static
    static_dir: static

  - url: /.*
    script: auto
