runtime: python39
runtime_config:
    
    runtime_version: "3.9.16"


entrypoint: gunicorn -b :8080 app:app

env_variables:
  GOOGLE_APPLICATION_CREDENTIALS: 'static/tts-key.json'

handlers:
  - url: /static
    static_dir: static

  - url: /.*
    script: auto

