runtime: python39
runtime_config:
    
    runtime_version: "3.9.16"


entrypoint: gunicorn -b :4000 main:app


env_variables:
  GOOGLE_APPLICATION_CREDENTIALS: 'static/tts-key.json'

handlers:
  - url: /static
    static_dir: static

  - url: /.*
    script: auto
